[pytest]
DJANGO_SETTINGS_MODULE = library_project.settings
python_files = tests.py test_*.py *_tests.py
addopts = 
    -v
    --tb=short
    --strict-markers
    --disable-warnings
markers =
    django_db: тест потребує взаємодії з базою даних
    models: тести бізнес-логіки моделей
    books: тести каталогу книг та фільтрів
    borrowings: тести позик
    auth: тести реєстрації та токенів